build: Standardize clang and llvm
This is to support build directly from host system easier. No change for
docker build.

Signed-off-by: Tam Mach <tam.mach@cilium.io>

diff --git a/Makefile.dev b/Makefile.dev
--- a/Makefile.dev
+++ b/Makefile.dev
@@ -57,18 +57,18 @@ compile_commands.json: WORKSPACE $(TIDY_SOURCES) force-non-root
 # Default number of jobs, derived from available memory
 TIDY_JOBS ?= $$(( $(shell sed -n "s/^MemAvailable: *\([0-9]*\).*\$$/\1/p" /proc/meminfo) / 4500000 ))
 
-# tidy uses clang-tidy-18, .clang-tidy must be present in the project directory and configured to
+# tidy uses run-clang-tidy, .clang-tidy must be present in the project directory and configured to
 # ignore the same headers as .clangd. Unfortunately the configuration format is different.
 tidy: compile_commands.json force-non-root
-	run-clang-tidy-18 -quiet -extra-arg="-Wno-unknown-pragmas" -checks=misc-include-cleaner -j $(TIDY_JOBS) $(TIDY_SOURCES) || echo "clang-tidy check failed, run 'make tidy-fix' locally to fix tidy errors."
+	run-clang-tidy -quiet -extra-arg="-Wno-unknown-pragmas" -checks=misc-include-cleaner -j $(TIDY_JOBS) $(TIDY_SOURCES) || echo "clang-tidy check failed, run 'make tidy-fix' locally to fix tidy errors."
 
 tidy-fix: compile_commands.json force-non-root
 	echo "clang-tidy fix results can contain duplicate or misplaced includes, check before committing!"
-	run-clang-tidy-18 -fix -format -style=file -quiet -extra-arg="-Wno-unknown-pragmas" -checks=misc-include-cleaner -j $(TIDY_JOBS) $(TIDY_SOURCES) || echo "clang-tidy fix produced changes, please commit them."
+	run-clang-tidy -fix -format -style=file -quiet -extra-arg="-Wno-unknown-pragmas" -checks=misc-include-cleaner -j $(TIDY_JOBS) $(TIDY_SOURCES) || echo "clang-tidy fix produced changes, please commit them."
 
 tidy-fix-head: compile_commands.json force-non-root
 	echo "clang-tidy fix results can contain duplicate or misplaced includes, check before committing!"
-	run-clang-tidy-18 -fix -format -style=file -quiet -extra-arg="-Wno-unknown-pragmas" -checks=misc-include-cleaner -j $(TIDY_JOBS) $(shell git diff-tree --no-commit-id --name-only -r --diff-filter=d HEAD) || echo "clang-tidy fix produced changes, please commit them."
+	run-clang-tidy -fix -format -style=file -quiet -extra-arg="-Wno-unknown-pragmas" -checks=misc-include-cleaner -j $(TIDY_JOBS) $(shell git diff-tree --no-commit-id --name-only -r --diff-filter=d HEAD) || echo "clang-tidy fix produced changes, please commit them."
 
 format: force-non-root
 	CARGO_BAZEL_REPIN=true $(BAZEL) $(BAZEL_OPTS) run $(BAZEL_BUILD_OPTS) @envoy//tools/code_format:check_format -- --path "$(PWD)" --skip_envoy_build_rule_check --add-excluded-prefixes $(FORMAT_EXCLUDED_PREFIXES) --bazel_tools_check_excluded_paths="./" --build_fixer_check_excluded_paths="./" check || echo "Format check failed, run 'make format-fix' locally to fix formatting errors."
