ci: validate envoy version format
[ upstream commit 3bd1a112631abe3ee5e86e959c445019229f49d3 ]

validate the envoy version to prevent injection attacks

Reported-by: Aviv Don <avivdon21@gmail.com>
Signed-off-by: Peter Oyekunle <poyekunl@cisco.com>
Signed-off-by: Tam Mach <tam.mach@cilium.io>

diff --git a/.github/workflows/build-envoy-image-ci.yaml b/.github/workflows/build-envoy-image-ci.yaml
--- a/.github/workflows/build-envoy-image-ci.yaml
+++ b/.github/workflows/build-envoy-image-ci.yaml
@@ -55,8 +55,15 @@ jobs:
       - name: Prep for build
         run: |
           echo "${{ github.event.pull_request.head.sha }}" >SOURCE_VERSION
-          echo "ENVOY_MINOR_RELEASE=$(cat ENVOY_VERSION | sed 's/envoy-\([0-9]\+\.[0-9]\+\)\..*/v\1/')" >> $GITHUB_ENV
-          echo "ENVOY_PATCH_RELEASE=$(cat ENVOY_VERSION | sed 's/^envoy-\([0-9]\+\.[0-9]\+\.[0-9]\+$\)/v\1/')" >> $GITHUB_ENV
+          VERSION=$(cat ENVOY_VERSION)
+          if [[ "$VERSION" =~ ^envoy-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            PATCH="${VERSION#envoy-}"
+            MINOR="${PATCH%.*}"
+            echo "ENVOY_MINOR_RELEASE=v${MINOR}" >> $GITHUB_ENV
+            echo "ENVOY_PATCH_RELEASE=v${PATCH}" >> $GITHUB_ENV
+          else
+            echo "Invalid ENVOY_VERSION format: '$VERSION'" && exit 1
+          fi
           echo "BUILDER_DOCKER_HASH=$(git ls-tree --full-tree HEAD -- ./Dockerfile.builder | awk '{ print $3 }')" >> $GITHUB_ENV
 
       - name: Checking if cilium-envoy-builder image exists
